
[basic]
home = "node0"
key_file = "node_key.json"
genesis_file = "genesis.json"
db_backend = "goleveldb"
db_dir = "data"
app = "kvstore"

[p2p]
home = "node0"
listen_address = "tcp://0.0.0.0:26656"
addr_book = "config/addrbook.json"
flush_duration = "100ms"
max_packet_msg_payload_size = "1024"
send_rate = "5120000"
recv_rate = "5120000"
pong_timeout = "45s"
ping_interval = "1m30s"
neighbours = "[81da6eddc2a1e3010c90@127.0.0.1:26656 aa3e21546f4d4acc983a@127.0.0.1:26657 9032ac7d29df8f426528@127.0.0.1:26658 8bc7e3744056c6bc0173@127.0.0.1:26659]"

[txs_pool]
home = "node0"
max_size = "2000"
max_tx_bytes = "1024"

[consensus]
home = "node0"
timeout_prepare = "3s"
timeout_pre_commit = "1s"
timeout_commit = "1s"
timeout_decide = "1s"
